sensor_msgs/Image image
sensor_msgs/CompressedImage compressed_image
string[] queries
---
jsk_recognition_msgs/ClassificationResult classes
jsk_recognition_msgs/RectArray rects
bool done
---
string status
