#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Publish std_msgs/Header with current timestamp.
This is to send a header request to image_view/image_saver.

Usage: rosrun image_view publish_header header:=<topic_0>
"""

import rospy
from std_msgs.msg import Header


def main():
    pub = rospy.Publisher('header', Header, queue_size=1)
    if 'header' not in rospy.names.get_mappings():
        rospy.logwarn("""
publish_header: topic 'header' is not remapped! Typical command-line usage:
\t$ rosrun image_view publish_header header:=<header_topic>""")
    rospy.sleep(1)  # wait for publisher to be registered
    msg = Header()
    msg.stamp = rospy.Time.now()
    pub.publish(msg)


if __name__ == '__main__':
    rospy.init_node('publish_header')
    main()
